name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  python-lint:
    runs-os: ubuntu-latest
    name: CI Workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2
    
    - name: linting
      uses: kingpack/pylinter@v1.0.0
      with:
        python-root: '.'
        flake8-flags: ''
        mypy-flags: ''
        fail-on-isort: false
        
    - name: commit isort changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort'
        
    - name: push isort changes
      uses: ad-m/github-push-actions@v0.5.0
      with:
         github_token: ${{ secrets.GH_ACCESS_TOKEN }}
         branch: ${{ github.ref }}
    
